spring:
  application:
    # 应用名称
    name: learn-order
    # 数据库的配置  jpa mysql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_cloud?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    # 注意 这里是 带cj的
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 显示sql
    show-sql: true
  main:
    # 覆盖设置
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      # 注册中心的地址
      defaultZone: http://localhost:8878/eureka
  instance:
    # 这个 可以修改 注册中心的 host
    hostname: localhost

server:
  # 启动端口
  port: 5001

# 自定义 服务器选取规则
#NFLoadBalancerClassName: 配置ILoadBalancer的实现类
#NFLoadBalancerRuleClassName: 配置IRule的实现类
#NFLoadBalancerPingClassName: 配置IPing的实现类
#NFWSServerListClassName: 配置ServerList的实现类
#NIWSServerListFilterClassName: 配置ServerListFilter的实现类
LEARN-PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule