#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003
spring:
  application:
  # 微服务的名字
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
    #服务注册中心的地址
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/
  instance:
    # host name 在eureka中配置的
    hostname: product-data-service
    # 为true就显示的是ip地址了 这里还需要调整一下 显示域名
    prefer-ip-address: true