server:
  port: 8878
eureka:
  instance:
    hostname: localhost
  client:
    # 自己要不要注册
    registerWithEureka: false
    fetchRegistry: false
    fetch-registry: false
    # 注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 
spring:
  application:
    # 服务名称
    name: eureka-server