server:
  # 端口
  port: 8002

eureka:
  instance:
    # 主机名 自定义链接
    hostname: localhost
    #访问路径可以显示ip地址
    prefer-ip-address: true
  client:
    # 注册地址
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8003/eureka/
    # 是否将自己注册到Eureka Server 默认为true
    register-with-eureka: true
    #是否从Eureka Server查询注册信息
    fetch-registry: false
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 清理服务间隔4s，默认60*10000
    eviction-interval-timer-in-ms: 4000

spring:
  application:
    # 服务名称 应用名称，也是服务注册的名称
    name: eureka-server